package level0;

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * 
 * ANSWER: 4613732
 */

public class Problem02EvenFibonacci {
	public static void main(String[] args) {
		int n1 = 1;
		int n2 = 2;
		int n3 = 0;
		int sum = 2;
		
		int highestNumber = 4000000;
		while (n3 < highestNumber) {
			n3 = n1 + n2;
			n1 = n2;
			n2 = n3;
			if (n3 & 1 == 0) sum += n3;
		}
		
		System.out.println("The sum of even Fibonacci numbers are " + sum);
	}
}
